server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api

spring:
  # TODO : PUSH ?? ?? ?? ?? ??? ?.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/candy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    url: ENC(5AbbdHbztmfwcCvgOiInLTu+C+wdNgAvcFgg71Ji0k156RWAuHc5ZoPrvjoBxiXMOIqcFddO4DCsH9zDJgP+p8tsTRzHjfM2YUeERHIojZoRfV4opJ1a1or3mzZU/sXcYAf/ODE+pgg=)
    username: ENC(AIFR+mKGggWIGjd4p+b4IQ==)
    password: ENC(Dfk7b2L35haa7meM4NYs9tILRFKeRtl7)